version: "3.8"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=skip_django
      - POSTGRES_PASSWORD=skip_django
      - POSTGRES_DB=skip_django_dev
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.26
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@skip.com
      - PGADMIN_DEFAULT_PASSWORD=skip_django
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    links:
      - db:pgsql-server

volumes:
  postgres_data:
  pgadmin_data:
