version: "3.8"

services:
  web:
    build:
      context: ./app
      dockerfile: dockerfile.prod
    command: gunicorn skip_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web
  pgadmin:
    image: dpage/pgadmin4:4.26
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@skip.com
      - PGADMIN_DEFAULT_PASSWORD=skip_django
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    links:
      - db:pgsql-server

volumes:
  postgres_data:
  pgadmin_data:
  static_volume:
  media_volume:
