# Generated by Django 3.0.10 on 2020-12-29 10:09

from django.db import migrations, models
import django.utils.timezone
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty_order', models.DecimalField(decimal_places=0, max_digits=5)),
                ('total_order', models.DecimalField(decimal_places=0, max_digits=12)),
                ('uang_bayar', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('kembalian', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='MenuWarteg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makanan', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(blank=True, max_length=255, null=True)),
                ('tipe', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=0, max_digits=12)),
                ('qty_menu', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('invoices', models.ManyToManyField(blank=True, related_name='invoices_menu', to='warteg_nusantara.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='BahanMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bahan', models.CharField(max_length=255)),
                ('qty_bahan', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('satuan', django_measurement.models.MeasurementField(measurement=measurement.measures.mass.Mass)),
                ('menus', models.ManyToManyField(blank=True, related_name='bahan_menu', to='warteg_nusantara.MenuWarteg')),
            ],
        ),
    ]
