# Generated by Django 3.0.10 on 2020-12-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warteg_nusantara', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bahanmenu',
            name='satuan',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
